## PANDAS

In [2]:
import pandas as pd

In [12]:
series = pd.Series(['apple', 'banana', 'cherry'])

In [13]:
series
#series are 1 dimensional arrays

0     apple
1    banana
2    cherry
dtype: object

In [14]:
colors = pd.Series(['red', 'yellow', 'red'])

In [15]:
food_color = pd.DataFrame({"Fruit": series, "Color": colors})
food_color
#Dataframes are 2 dimensional arrays

    Fruit   Color
0   apple     red
1  banana  yellow
2  cherry     red

In [16]:
#Import Data
car_data = pd.read_csv("/Users/kamari/Downloads/car-sales.csv")

In [17]:
#export a dataframe
car_data.to_csv("exported-car-sales.csv", index=False)

In [18]:
car_data

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

In [19]:
car_data[car_data['Colour'] == 'White']

     Make Colour  Odometer (KM)  Doors      Price
0  Toyota  White         150043      4  $4,000.00
4  Nissan  White         213095      4  $3,500.00
8  Toyota  White          60000      4  $6,250.00
9  Nissan  White          31600      4  $9,700.00

## NUMPY

In [2]:
import numpy as np

In [3]:
a1 = np.array([1,2,3,4])
a1

array([1, 2, 3, 4])

In [4]:
a2 = np.array([[1,2.0,3,4],
               [5,6,7,8.0]])

a3 = np.array([[[1,2,3,4],
                [5,6,7,8]],
               [[9,10,11,12],
                [13,14,15,16]]])
a3

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [32]:
a1.shape

(4,)

In [5]:
df = pd.DataFrame(a2)
df

NameError: name 'pd' is not defined

In [6]:
ones = np.ones((4,5))
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [21]:
range_a = np.random.random((3,4))
range_a

array([[0.25224856, 0.24170972, 0.74619424, 0.01322093],
       [0.22829319, 0.09379841, 0.26550829, 0.96186915],
       [0.70525388, 0.21151517, 0.57647675, 0.71268635]])

In [137]:
np = np.array([1,2,3,4,5,6,7,8,9,10])
np

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Exercises

In [11]:
ex_1 = np.array([1,2,3,4,5])
ex_1_2 = np.array([
        [1,2,3,4],
        [5,6,7,8]
])
np.unique(ex_1)

array([1, 2, 3, 4, 5])

In [8]:
ex2 = np.array([1,2,3,4,5])
ex2 * 2
ex2 + 10
ex2 ** 2

array([ 1,  4,  9, 16, 25])

In [9]:
ex_3 = np.array([[4, 5, 6],
                 [7, 8, 9],
                 [10, 11, 12],
                 [13, 14, 15]
                 ])
ex_3[1:2, 1:2]
#ex_3[:1]
#ex_3[-1:]

#ex_3[:1,:1]
ex_3[1:2, 1:2]

array([[8]])

In [110]:
ex_3.shape

(4, 3)

In [136]:
ex_4 = np.array([1,2,3,10,23,10,20])
ex_4> 10
ex_4 % 2 == 0

array([False,  True, False,  True, False,  True,  True])

In [ ]:
#Variance = measure of how spread out a group of numbers is from the mean 
#Higher variance = more spread out
#Lower variance = less spread out
np.var(ex_1)

np.float64(2.0)

In [16]:
#Standard Deviation = square root of the variance
np.sqrt(np.var(ex_1))

np.float64(1.4142135623730951)

In [36]:
low_v_arr = np.array([[2,4,6], 
                      [7,8,10]])

high_v_arr = np.array([[2,44],
                       [59,62],
                       [1023, 1280]])

In [18]:
np.var(high_v_arr), np.var(low_v_arr)

(np.float64(159111.38775510204), np.float64(8.0))

In [ ]:
np.std(ex_1)

reshape and transpose

In [214]:
low_v_arr * high_v_arr

ValueError: operands could not be broadcast together with shapes (2,3) (3,2)

In [37]:
low_v_arr.shape , high_v_arr.shape

((2, 3), (3, 2))

In [ ]:
low_v_arr.T * high_v_arr

low_v_arr = np.array([[2,4,6], 
                      [7,8,10]])

high_v_arr = np.array([[2,44],
                       [59,62],
                       [1023, 1280]])

array([[    4,   308],
       [  236,   496],
       [ 6138, 12800]])

In [ ]:
ex_5 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
ex_5  = ex_5.reshape(3,4)
ex_5
ex_5[1:2, 3:4]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [169]:
ex_6 = np.arange(1,13)
ex_6  = ex_6.reshape(2,6)
ex_6
ex_6.T

ex_6.T[3:4, 1:]
ex_6.T[3,1]

np.int64(10)

In [ ]:
test1 = np.arange(1,17)
test1 = test1.reshape(4,4)
test1 = test1.T
test1 = test1.flatten()
test1
test1[7]

array([ 1,  5,  9, 13,  2,  6, 10, 14,  3,  7, 11, 15,  4,  8, 12, 16])

In [190]:
test1[7]

np.int64(14)

In [187]:
test1.flatten()

array([ 1,  5,  9, 13,  2,  6, 10, 14,  3,  7, 11, 15,  4,  8, 12, 16])

turn image into array

In [221]:
#Excersise Nutty Butter
from matplotlib.image import imread

panda = imread("/Users/kamari/Downloads/numpy-images/panda.png")
panda

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       ...,

       [[0.13333334, 0.07450981, 0.05490196],
        [0.12156863, 0.0627451 , 0.04313726],
        [0.10980392, 0.05098039, 0.03137255],
        ...,
        [0.02745098, 0.02745098, 0.03529412],
        [0.02745098, 0.02745098, 0.03529412],
        [0.02745098, 0.02745098, 0.03529412]],

       [[0.13333334, 0.07450981, 0.05490196],
        [0.12156863, 0.0627451 , 0.04313726],
        [0.12156863, 0.0627451 , 0.04313726],
        ...,
        [0.02352941, 0.02352941, 0.03137255],
        [0.02352941, 0.02352941, 0.03137255],
        [0.02352941, 0.02352941, 0.03137255]],

       [[0.13333334, 0.07450981, 0.05490196],
        [0.12156863, 0.0627451 , 0.04313726],
        [0.12156863, 0.0627451 , 0.04313726],
        ...,
        [0.02352941, 0.02352941, 0.03137255],
        [0.02352941, 0.02352941, 0.03137255],
        [0.02352941, 0.02352941, 0.03137255]]],
      shape=(2330, 3500, 3), dtype=float32)

## MATPLOTLIB