In [1]:
import pandas as pd

In [4]:
series = pd.Series(['apple', 'banana', 'cherry'])

In [5]:
series
#series are 1 dimensional arrays

0     apple
1    banana
2    cherry
dtype: object

In [7]:
colors = pd.Series(['red', 'yellow', 'red'])

In [9]:
food_color = pd.DataFrame({"Fruit": series, "Color": colors})
food_color
#Dataframes are 2 dimensional arrays

    Fruit   Color
0   apple     red
1  banana  yellow
2  cherry     red

In [12]:
#Import Data
car_data = pd.read_csv("/Users/kamari/Downloads/car-sales.csv")

In [ ]:
#export a dataframe
car_data.to_csv("exported-car-sales.csv", index=False)

In [13]:
car_data

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

In [37]:
car_data[car_data['Colour'] == 'White']

     Make Colour  Odometer (KM)  Doors      Price
0  Toyota  White         150043      4  $4,000.00
4  Nissan  White         213095      4  $3,500.00
8  Toyota  White          60000      4  $6,250.00
9  Nissan  White          31600      4  $9,700.00